version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=5000  # Only run Flask here, migrations will be handled separately
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - FLASK_APP=app.py
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: python_crud_app
    ports:
      - "5432:5432"
